version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: main-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - main-network
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
  app:
    container_name: main-app
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/main
    depends_on:
      - database
      - composer_installation
    networks:
      - main-network
  web:
    image: nginx:latest
    container_name: main-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/main
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - main-network
  redis:
    image: redis:alpine
    container_name: main-redis
    ports:
      - "6379:6379"
    networks:
      - main-network
  elasticsearch:
    image: elasticsearch:8.4.0
    container_name: main-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - main-network
  kibana:
    image: kibana:8.4.0
    container_name: main-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - main-network
networks:
  main-network:
    driver: bridge