version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: main-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - main-network
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
  app:
    container_name: main-app
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/main
    depends_on:
      - database
      - composer_installation
    networks:
      - main-network
  web:
    image: nginx:latest
    container_name: main-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/main
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - main-network
networks:
  main-network:
    driver: bridge