api_refresh_token:
  path: /api/auth/token/refresh

api_token_invalidate:
  path: /api/auth/token/invalidate

api_login_check:
  path: /api/auth/login

controllers:
  resource: ../src/Controller
  type: attribute

api_controllers:
  resource: ../src/Controller/Api
  type: attribute
  prefix: api

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
